services:

    redis:
        container_name: redis-2
        image: redis
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning
    backend:
        build: .
        container_name: backend-2
        command: gunicorn core.wsgi --bind 0.0.0.0:8080
        volumes:
            - ./core:/app
            - static_volume:/app/static
            - media_volume:/app/media
        expose:
            - "8080"
        environment:
            - SECRET_KEY=test
            - DEBUG=True
        depends_on:
            - redis
    celery_worker:
        build: .
        working_dir: /app
        command: celery -A core worker --loglevel=info
        volumes:
            - ./core:/app
        depends_on:
            - redis
            - backend
    nginx:
        image: nginx
        container_name: nginx-2
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/home/app/static
            - media_volume:/home/app/media
        depends_on:
            - redis
            - backend
volumes:
  static_volume:
  media_volume: