services:
    redis:
        container_name: redis-2
        image: redis
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning
    backend:
        build: .
        container_name: backned
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - ./core:/app
        ports:
            - "8080:8080"
        environment:
            - SECRET_KEY=test
            - DEBUG=True
        depends_on:
            - redis
    celery_worker:
        build: .
        working_dir: /app
        command: celery -A core worker --loglevel=info
        volumes:
            - ./core:/app
        depends_on:
            - redis
            - backend
    celery_beat:
        build: .
        working_dir: /app
        command: celery -A core beat --loglevel=info
        volumes:
            - ./core:/app
        depends_on:
            - redis
            - backend
    smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            - '5020:80'
        volumes:
            - smtp4dev-data:/smtp4dev
        environment:
            - ServerOptions_HostName=smtp4dev

volumes:
    smtp4dev-data:
